blank_issues_enabled: false

contact_links:
  - name: 📚 Project Wiki 
    url: https://github.com/DSivtsov/SeaWind/wiki
    about: "Ознакомьтесь с описанием проекта и документацией перед созданием issue."

  - name: 📘 Backlog Workflow Guide
    url: https://github.com/DSivtsov/SeaWind/wiki/Backlog_Workflow_Guide
    about: "Backlog Workflow Guide — описывающий, как мы организуем совместную работу над проектом через GitHub Projects."
