name: Epic
description: Создайте высокоуровневую задачу (Epic)
title: "[EPIC] "
labels: ["EPIC"]
assignees: []   # Эпики не назначаются конкретным исполнителям
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Список основных подфункций, входящих в данный Epic"
      placeholder: |
        * Регистрация
        * Авторизация
    validations:
      required: true

  - type: textarea
    id: substories
    attributes:
      label: User Stories (Sub-issues)
      description: "Список связанных User Story (удобнее добавить после создания Epic через *Create sub-issue*)"
      placeholder: |
        #<user-story-id>
