name: Task
description: Создайте описание технической задачи (часть User Story)
title: "Task: "
labels: ["TASK"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Что нужно реализовать или исправить?"
      placeholder: "Реализовать POST /api/auth/register ..."
    validations:
      required: true

  - type: textarea
    id: tech-notes
    attributes:
      label: Technical Notes (optional)
      description: "Архитектурные решения, библиотеки, важные детали реализации"
      placeholder: "- Использовать ASP.NET Identity\n- Хэшировать пароль через PasswordHasher"
    validations:
      required: false

  - type: textarea
    id: out-of-scope
    attributes:
      label: Out of Scope (optional)
      description: "Что явно не входит в этот Task"
      placeholder: "- В этой задаче не реализуем social login"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: "Условия, при которых Task считается выполненным"
      placeholder: |
        * Сборка проходит (`dotnet build -c Release`)
        * Тесты проходят (`dotnet test -c Release --no-build`)
        * API-документация обновлена (Swagger)
    validations:
      required: true
