name: User Story
description: Создайте и опишите User Story
title: "User Story: "
labels: ["USER STORY"]
body:
  - type: input
    id: role
    attributes:
      label: As a
      placeholder: Student / FreeStudent / Mentor / Admin / Guest
    validations:
      required: true

  - type: input
    id: goal
    attributes:
      label: I want
      placeholder: Описание того, что пользователь хочет получить или сделать
    validations:
      required: true

  - type: input
    id: value
    attributes:
      label: So that
      description: Зачем это нужно пользователю (какую проблему решает, какую ценность даёт)

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes (optional)
      description: "Указание основных технологий (решений): APIs, DB tables, etc."

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Перечень конкретных пунктов, которые должны быть выполнены
      placeholder: |
        * Поля «логин», «пароль» и «email» обязательны для заполнения.
        * При успешной регистрации создаётся новая учётная запись.
        * После регистрации происходит автоматический вход в систему.
    validations:
      required: true

  - type: textarea
    id: tasks-subissues
    attributes:
      label: Tasks (Sub-issues)
      description: "Список связанных TASK (удобнее добавить после создания User Story через *Create sub-issue*)."
      placeholder: |
        #<task-id>
